### ISSUE TITLE
Optimization of Workflows

### ISSUE THREAD

**Issue by JankKeks** [T-Systems-MMS/phonebook#11]
Reduce number of clicks for typical workflows:
- f.e. add copy Button next to Mail/Phone
- f.e. add dail Button next to Phone
Enable copy and paste by selecting text by mouse in Buttons "mat-buttons"

**Comment by mschwrdtnr** [comment]
I think that it would be cool if the copy button will appear on the right side on hover. The advantage is, that the User-Page won't look full packed.

**Comment by mschwrdtnr** [comment]
Would be good if this will also be implemented for the bookmarked persons.

**Comment by mschwrdtnr** [comment]
Hey @paule96 & @DanielHabenicht, what do you think about a solution like that?
https://i.gyazo.com/436967bade666b5c69ef7c0ab5ff7bf8.mp4

**Comment by paule96** [comment]
> Hey @paule96 & @DanielHabenicht, what do you think about a solution like that?
> https://i.gyazo.com/436967bade666b5c69ef7c0ab5ff7bf8.mp4
> ..i am not sure if we still need the actiondrawer with a solution like that

The best for should be that we use a setting so the user can define whats happend. Because I only see here two options what should happend if I click on something like this. 

- start a application that know what todo (telefon -> open skype, email -> open mail app)
- Copy the text by click

I think that is the easiest way to do it. maybe @JankKeks has some more advanced input.
