### ISSUE TITLE
Possibility to hide recent searched people

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#277]
Possibility to hide "Recent People" on dashboard.  

Idea: Toggle for the right side like on the room-page.

**Comment by friedaxvictoria** [comment]
@DanielHabenicht Hi, I just started this issue. Frank suggested adding the 'Toggle' to th local Storage. I just wanted to ask if this is something I should try to implement and if so how to add the function to the component.

**Comment by DanielHabenicht** [comment]
Yep, just be aware that in order to persist data you just have to add the state class to the storage plugin and it will be automatically persisted. https://github.com/T-Systems-MMS/phonebook/blob/80fb7f11790391b41428871d41d2ddad4c768080/Phonebook.Frontend/src/app/app.module.ts#L74
Or you can put the state into: 
https://github.com/T-Systems-MMS/phonebook/blob/master/Phonebook.Frontend/src/app/shared/states/App.state.ts
