### ISSUE TITLE
Make a more stable vs and formating configuration

### ISSUE THREAD

**Issue by paule96** [T-Systems-MMS/phonebook#350]
> #### This is a public issue tracker. 
> #### Be sure that your description and screenshots not contain any personal or company info.

**Is your feature request related to a problem? Please describe.**

Try to solve formatting issues for new phonebook developers. See the PR #348.

**Describe the solution you'd like**

There are some solutions out there. We can try to make this happend with only a vscode config. But I don't know if this is possible. What I also see often is a editor config. But that requieres a new extensions for all phonebook developers.

**Comment by mschwrdtnr** [comment]
I also think that we need something like you sayd. And i think that we should not force people to use vscode if they are not familiar with.

A good solution could be an github action which checks the code and make a new commit with the corrected code styles. Maybe this could be the right moment to use a [code review app](https://github.com/marketplace/category/code-review)? 
On the first look i found [restyled.io](https://github.com/marketplace/restyled-io) which setting up restyled prs 🤔

**Comment by marcuskrahl** [comment]
In my opinion it is beneficial to also provide settings for each developers editor. A code review app might reduce white space changes for code reviews. However the code will still be formatted differently when a developer locally opens a file and introduce lots of noise in your local diff view.

There are different options for sharing format settings. At the low end there is something like [editorconfig](https://editorconfig.org/) which is almost universally supported, but only has limited configuration options. At the other end there is [prettier](https://prettier.io/) which guarantees that code looks the same in every editor with its opinionated approach. I know that @DanielHabenicht does not like prettiers HTML formatting so that may not be an option.

You can also define formatting options in [tslint](https://palantir.github.io/tslint/rules/#format), but this will be limited to typescript files.

**Comment by DanielHabenicht** [comment]
It hunk we are currently using prettier and I am happy to use it. So we can use prettier for everything.

**Comment by Zeroks77** [comment]
@DanielHabenicht  & @mschwrdtnr this can be closed, right ?

**Comment by mschwrdtnr** [comment]
I am not sure but think that #363 and #360 are a good base :)

**Comment by mschwrdtnr** [comment]
> @DanielHabenicht & @mschwrdtnr this can be closed, right ?

I am not sure but think that #363 and #360 are a good base :)

**Comment by mschwrdtnr** [comment]
@T-Systems-MMS/phonebook-admins what do you say, can be closed?

**Comment by mschwrdtnr** [comment]
> @T-Systems-MMS/phonebook-admins what do you say, can be closed?
