### ISSUE TITLE
Skillprofil Backend

### ISSUE THREAD

**Issue by Zeroks77** [T-Systems-MMS/phonebook#543]
Hey, guys, 

I would like to write the skill profile backend as part of my project work, I just need to know how far we want it to go. 

Also it would be cool if someone could build a frontend because I probably won't have enough time for that... 

According to IHK I only have 40h time for it. 

I would be happy about ideas and help :D 

@T-Systems-MMS/phonebook-developers

**Comment by mschwrdtnr** [comment]
My first thoughts about it:
- A user can choose Skills out of a big list (because if the user can write what he wants, it's not easy to search for; but maybe this is also okay)
- The maximum number of presented skills is 10 (the profile will not be overloaded)
- The user can present the skill on a scale (1 Star, 2 Stars, 3 Stars OR Beginner, Intermediate, Expert)
- I don't really know where the user should write in his skills and how this will be saved 🤔

**Comment by DanielHabenicht** [comment]
> * A user can choose Skills out of a big list (because if the user can write what he wants, it's not easy to search for; but maybe this is also okay)

Get the initial list of tags from StackOverflow, and then implement a form of managed tag creation, like allowing users to "create" new tags but also allowing admins to manage them in the background (like renaming, and merging) 
> * The maximum number of presented skills is 10 (the profile will not be overloaded)
I am against a maximum number of skills
> * The user can present the skill on a scale (1 Star, 2 Stars, 3 Stars OR Beginner, Intermediate, Expert)
+1 for beginner, intermediate
> * I don't really know where the user should write in his skills and how this will be saved 🤔
Thats what you have to program. 
I can provide a card in the user profile where he can add and delete tags ;)

There should be some internal discussion or documentation on what users want. Ask @paule96 for it. Something that I know did come up was, a label for each person where they can show if the are free to contact or busy (in order to not get overloaded with questions to a specific topic). Also the option to temporarily hide the skills from all. 

Other ideas that are in the backlog are showing current and past projects of the person.

**Comment by DanielHabenicht** [comment]
@Zeroks77 :(

**Comment by Zeroks77** [comment]
@DanielHavent 
I had talked to my instructor, maybe I will build it later, but for my IHK exam I have to do something that I can present better.

Until then I would close it for now, because the text above is not right.
